CREATE OR REPLACE FUNCTION ATUALIZAR_PASSAGEIRO(
    _ID_ITEM_RESERVA INT, 
    _CPF VARCHAR, 
    _NOME VARCHAR
)
RETURNS VOID AS $$
BEGIN 
    UPDATE ITEM_RESERVA 
    SET CPF_PASSAGEIRO = _CPF, NOME_PASSAGEIRO = _NOME 
    WHERE ID_ITEM_RESERVA = _ID_ITEM_RESERVA;
    RAISE NOTICE 'PASSAGEIRO alternado com sucesso!',
_NOME;
    END;
$$ LANGUAGE PLPGSQL;


CREATE OR REPLACE FUNCTION ATUALIZAR_DESCRICAO_CLASSE(_ID_CLASSE INT, _DESCRICAO TEXT)
RETURNS VOID AS $$
BEGIN
    UPDATE CLASSE SET DESCRICAO = _DESCRICAO WHERE ID_CLASSE = _ID_CLASSE;
    RAISE NOTICE 'ATUALIZACAO REALIZADA COM SUCESSO';
    END;
$$ LANGUAGE PLPGSQL;