/*
 =========================================
 ||                                     ||
 ||    Função para Verificar Assentos   ||
 ||       Disponíveis em um Voo         ||
 =========================================
 */
CREATE
OR REPLACE FUNCTION VERIFICAR_ASSENTOS_DISPONIVEIS(_ID_VOO INT) RETURNS TABLE (ID_ASSENTO INT, NOME_CLASSE VARCHAR) AS $ $ BEGIN RETURN QUERY
SELECT
    a.ID_ASSENTO,
    c.NOME AS NOME_CLASSE
FROM
    AVIAO_ASSENTO_CLASSE_VOO a
    JOIN CLASSE c ON a.ID_CLASSE = c.ID_CLASSE
WHERE
    a.ID_VOO = _ID_VOO
    AND a.STATUS = FALSE;

END $ $ LANGUAGE plpgsql;

 
    /*
    VERIFICAR PASSAGEIROS INCLUSOS NO VOO N°121
    */

    /*
    VERIFICAR RESERVAS ASSOCIADAS AO PASSAGEIRO DE ID 122
    */

    /*
    VERIFICAR PASSAGENS POR RESERVA
    */

    /*
    VERIFICAR CLASSE QUE MAIS SE ASSOCIOU A RESERVAS EM DETERMINADO PERÍODO
    */

    /*
    VERIFICAR ASSENTOS OCUPADOS POR VOO
    */

    /*
    VERIFICAR RECEITA GERADA POR VOO
    */

    /*
    MOSTRAR TODOS OS VOOS POR DETERMINADA DATA COM SEUS HORÁRIOS
    */

    /*EXIBIR INFORMAÇÕES SOBRE VOOS E SEUS TRAJETOS
    */

    /*MOSTRAR QUANTAS PASSAGENS UM USUÁRIO TEM PARA CADA VOO
    */