    /*
    VERIFICAR PASSAGEIROS INCLUSOS NO VOO N°121
    */

    /*
    VERIFICAR RESERVAS ASSOCIADAS AO PASSAGEIRO DE ID 122
    */

    /*
    VERIFICAR PASSAGENS POR RESERVA
    */

    /*
    VERIFICAR RESERVAS POR FUNCIONÁRIO
    */

    /*
    VERIFICAR CLASSE QUE MAIS SE ASSOCIOU A RESERVAS EM DETERMINADO PERÍODO
    */

    /*
    VERIFICAR ASSENTOS OCUPADOS POR VOO
    */

    /*
    VERIFICAR RECEITA GERADA POR VOO
    */

    /*
    MOSTRAR TODOS OS VOOS POR DETERMINADA DATA COM SEUS HORÁRIOS
    */

    /*
    RESERVAS POR MÉTODO DE PAGAMENTO
    */

    /*EXIBIR INFORMAÇÕES SOBRE VOOS E SEUS TRAJETOS
    */

    /*MOSTRAR QUANTAS PASSAGENS UM USUÁRIO TEM PARA CADA VOO
    */